# Generated by Django 3.2.5 on 2021-07-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('full time', 'part time'), ('part time', 'full time')], default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
