# Generated by Django 3.2.5 on 2021-09-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='img',
            field=models.ImageField(default='', max_length=256, upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
