# Generated by Django 3.2.5 on 2021-07-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='excprince',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobs',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobs',
            name='vacancy',
            field=models.IntegerField(default=1),
        ),
    ]
