# Generated by Django 3.2.5 on 2021-08-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='img',
            field=models.ImageField(default='', max_length=256, upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
