# Generated by Django 3.2.5 on 2021-08-15 22:11

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobs_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='img',
            field=models.ImageField(max_length=256, upload_to=jobs.models.img_name),
        ),
    ]
