# Generated by Django 3.2.7 on 2021-09-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='obj',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
