# Generated by Django 3.2.5 on 2021-08-27 21:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='eg', max_length=2),
            preserve_default=False,
        ),
    ]
